dtb-$(CONFIG_ARCH_MSM8998) += \
	msm8998-mtp_NB1_EVB.dtb \
	msm8998-mtp_NB1_EVB1.dtb \
	msm8998-mtp_NB1_EVB2.dtb \
	msm8998-mtp_NB1_EVT.dtb \
  msm8998-mtp_NB1_EVT0_5.dtb \
  msm8998-mtp_NB1_EVT1.dtb \
  msm8998-mtp_NB1_EVT1_SS.dtb \
  msm8998-mtp_NB1_DVT1.dtb \
  msm8998-mtp_NB1_DVT1_SS.dtb \
  msm8998-mtp_NB1_DVT1_CN.dtb \
  msm8998-mtp_NB1_DVT1_5.dtb \
  msm8998-mtp_NB1_DVT1_5_SS.dtb \
  msm8998-mtp_NB1_DVT1_5_CN.dtb \
  msm8998-mtp_NB1_DVT2.dtb \
  msm8998-mtp_NB1_DVT2_SS.dtb \
  msm8998-mtp_NB1_DVT2_CN.dtb \
  msm8998-mtp_NB1_PVT.dtb \
  msm8998-mtp_NB1_PVT_SS.dtb \
  msm8998-mtp_NB1_PVT_NR.dtb \
  msm8998-mtp_NB1_PVT1.dtb \
  msm8998-mtp_NB1_PVT1_SS.dtb \
  msm8998-mtp_NB1_PVT1_NR.dtb \
  msm8998-mtp_NB1_PVT1_Chile.dtb \
  msm8998-mtp_NB1_PVT1_Chile_SS.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
